const initialStoreItems = [
  {
    id: 1,
    name: "Beetroot",
    type: "vegetable",
    price: 0.5,
    image: "/assets/icons/001-beetroot.svg",
    description: "Fresh beetroot, perfect for salads and juices.",
  },
  {
    id: 2,
    name: "Carrot",
    type: "vegetable",
    price: 0.3,
    image: "/assets/icons/002-carrot.svg",
    description: "Crunchy and sweet carrots, great for snacking.",
  },
  {
    id: 3,
    name: "Apple",
    type: "fruit",
    price: 0.6,
    image: "/assets/icons/003-apple.svg",
    description: "Juicy and crisp apples, ideal for a healthy snack.",
  },
  {
    id: 4,
    name: "Apricot",
    type: "fruit",
    price: 0.7,
    image: "/assets/icons/004-apricot.svg",
    description: "Sweet and tangy apricots, great for desserts.",
  },
  {
    id: 5,
    name: "Avocado",
    type: "fruit",
    price: 1.5,
    image: "/assets/icons/005-avocado.svg",
    description: "Creamy avocados, perfect for guacamole.",
  },
  {
    id: 6,
    name: "Bananas",
    type: "fruit",
    price: 0.4,
    image: "/assets/icons/006-bananas.svg",
    description: "Ripe and sweet bananas, ideal for a quick snack.",
  },
  {
    id: 7,
    name: "Bell Pepper",
    type: "vegetable",
    price: 0.8,
    image: "/assets/icons/007-bell-pepper.svg",
    description: "Colorful bell peppers, great for salads and stir-fries.",
  },
  {
    id: 8,
    name: "Berry",
    type: "fruit",
    price: 2.0,
    image: "/assets/icons/008-berry.svg",
    description: "Mixed berries, perfect for smoothies and desserts.",
  },
  {
    id: 9,
    name: "Blueberry",
    type: "fruit",
    price: 1.8,
    image: "/assets/icons/009-blueberry.svg",
    description: "Sweet and tangy blueberries, ideal for snacking.",
  },
  {
    id: 10,
    name: "Eggplant",
    type: "vegetable",
    price: 1.0,
    image: "/assets/icons/010-eggplant.svg",
    description: "Versatile eggplants, perfect for grilling and baking.",
  },
];

export default initialStoreItems;
